### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by ManaalAhi** [mmurray/cvdn#7]
When I try to execute the train.py file with given example parametres, I get the following error: 

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
Traceback (most recent call last):
  File "tasks/NDH/train.py", line 253, in <module>
    train_val(path_type, max_episode_len, history, MAX_INPUT_LENGTH, feedback_method, n_iters, model_prefix, blind)
  File "tasks/NDH/train.py", line 191, in train_val
    dropout_ratio, bidirectional=bidirectional).cuda()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

I would be grateful if someone could tell me a solution to this.

**Comment by thomason-jesse** [comment]
Hi Manaal, are you running train.py from inside the docker container, and do your unit tests pass?
https://github.com/mmurray/cvdn#building-and-testing-using-docker

**Comment by ManaalAhi** [comment]
Hello, Yes my unit tests all pass. 
Also, another issue is that in the docker file to install pip, it uses easy install, however that behaviour seems to have been deprecated.

**Comment by mmurray** [comment]
Hi Manaal, thanks for letting us know about the easy_install usage in the Dockerfile. I just pushed a commit that uses a different method to install pip. I also tested that with the latest code the docker file builds and after you follow the installation instructions you can run training inside the docker container.

`cuDNN error: CUDNN_STATUS_EXECUTION_FAILED` I think generally happens when there is a mismatch between the torch/cuda/cudnn versions in your environment. This shouldn't happen if you use the docker container. I definitely recommend using the docker container for now because some of our dependencies are relatively old (I filed #8 to track the task of updating our dependencies but it's not something I plan on doing in the near future). For now I will close this issue but feel free to re-open if there is something we can do to help you with the CUDNN_STATUS_EXECUTION_FAILED error.

**Comment by WendyeeWang** [comment]
Our CUDA and Cudnn matches. However, we still cannot run it.

**Comment by LemonZhong** [comment]
Too many bugs! It is really really really hard to make it work in python3 environment
